import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// not sure if order matters here; without importing tailwind.css tailwind styles are not applied
import 'tailwindcss/tailwind.css';
import './styles/main.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
